### PR TITLE
Simplify the dialog's action process

### PR DESCRIPTION
**Pull request by samwilson**
Don't return the parent process within itself, remove half-second wait, and split dialog-closing into its own step.

Also use existing WindowManager rather than creating a new one.

Bug: T319463

### CODE REVIEW

**Review by MusikAnimal — COMMENTED** [review]
I knew you'd know what to do! Unfortunately though, this didn't work for me :( I'm testing at https://meta.wikimedia.org/wiki/User:MusikAnimal/AddMe-example and you should be able to as well (after starting your local server and loading the gadget in your global JS). `reloadContent()` is being called, but the response from the parse API is still the old content. I don't really believe that the action process is truly waiting for the initial promise to finish... or how else could the parse API possibly still be getting the old content _after_ an edit changed said content? I was beginning to believe that might be why the OOUI action process gave you the option to wait _N_ milliseconds.

Also the build should now fail thanks to #1 unless you commit the transpiled code as well.

**Comment by samwilson** [comment]
Sorry about my slow response here! I went around in a few circles with it.

I do think that there's some way to handle these as separate process steps, but actually that doesn't really matter if we resolve them within one.

See what you think.

**Comment by MusikAnimal** [comment]
This still did not work for me :( I'm guessing you aren't running into the issue I'm talking about? Internet connection speed may have something to do with it. Mine is very fast, and if yours is slower you may not be able to repro.

I put a `console.log` at the top of `submit()`, `updateSection()`, and `reloadContent()`, with latter two also having logging in the `then()` blocks to test when the promise was resolved. For `reloadContent`, I also printed the value of `wgRevisionId`. Here's the output:

```
submit()
updateSection
updateSection - resolved
reloadContent (rev ID = 23872935)
reloadContent - resolved (rev ID = 23872935)
```

Every time I test it's always in this order (which is correct), except I always get the same rev ID, which should _not_ happen. Re-reading my code, I'm starting speculate that the `then()`'s in `submit()` are perhaps not implemented as intended? It definitely feels like a promise isn't resolving properly.

Thanks for looking at this, and sorry to make you keep going back and forth!

**Comment by samwilson** [comment]
This is tricky! Sorry for not following properly. I think I've added similar logging to what you have, and am getting different revision IDs. I'm also testing this locally (as well as on your Meta example page) and in both wikis am getting the same results:

```
submit()
updateSection()
reloadContent() - initial ID 400
reloadContent() - resolved ID 401
```

I take it the error you're seeing is that the new support vote isn't ending up displayed? Because in all my tests, it *is* correctly displayed (i.e. the new revision is being returned, and inserted into the page). It does sound like a race condition though. I'll keep debugging...

**Comment by MusikAnimal** [comment]
Yes, the new comment is not displayed for me. Interesting that you're not running into this! It must be a race condition of some sort.

Thanks for looking into it :) I'm going to be doing some more debugging too once I finish [T319234](https://phabricator.wikimedia.org/T319234), so don't feel pressured to figure it out (especially since you can't repro!). Maybe we can debug together at the off-site.

**Comment by MusikAnimal** [comment]
The Editing team got back to me, and silly silly _silly_ me simply forgot we need to purge!!!! Of course that's why nothing is working as expected... (though I still find it odd you didn't encounter the issue at home in Australia)

I'm going to merge this as-is and iterate on it. Thanks so much for all the help! Even if we didn't solve the issue with this PR, you still really cleaned up the code.

**Pull request merged**
